#ifndef ZURELIB_ZL_TYPES_H
#define ZURELIB_ZL_TYPES_H

#define ZL_BOOL unsigned char

#define ZL_TRUE 1
#define ZL_FALSE 0

typedef enum
{
    ZL_SUCCESS = 0,
    ZL_COMMON_FAILURE = 0xDEADC0DE,
    ZL_INVALID_PARAMETER = 0xBAD00000,
    ZL_OUT_OF_MEMORY = 0xDEAD0000,
    ZL_NOT_IMPLEMENTED = 0xBADC0DED,
    ZL_NOT_SUPPORTED = 0xBADF00D,
    ZL_COMMON_DEADLOCK = 0xDEADBEEF,
} ZL_STATUS;

#endif // ZURELIB_ZL_TYPES_H